#!/bin/bash

# Kill existing docker
docker kill portainer
docker rm portainer

# Run portainer
docker run -d -p 8000:8000 -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v rfc_portainer:/data portainer/portainer-ce

