#!/bin/bash

# KILL IMAGES & REMOVE IMAGE & VOLUMES
docker_kill
docker image rm $(docker images -q)
docker volume rm $(docker volume ls -q)

# BUILD ALL IMAGE DEFINED (INCREMENTIAL)
docker build /home/docker/secureftp_base/. --tag="secureftp"
docker build /home/docker/secureftp_laravem/. --tag="secureftp_laravel"

# START ALL CONTAINER USING LOCAL DB
python docker_start.py

# CREATE ABSOLUTE LINK
ln -s /var/lib/docker/volumes /home/docker/mountpoint
